const Router = require('express')
const router = new Router()

const userRouter = require('../routes/userRouter')
const vehicleRouter = require('../routes/vehicleRouter')
const tariffPlanRouter = require('../routes/tariffPlanRouter')
const bonusesCostRouter = require('../routes/bonusesCostRouter')
const subscriptionProcessRouter = require('../routes/subscriptionProcessRouter')
const openAIRouter = require('../routes/openAIRouter')
const cancellationPoliciesRouter = require('../routes/cancellationPoliciesRouter')
const depositProcessRouter = require('../routes/depositProcessRouter')
const favouriteParkingRouter = require('../routes/favouriteParkingRouter')
const parkingActionRouter = require('../routes/parkingActionRouter')
const parkingRouter = require('../routes/parkingRouter')
const parkPlaceRouter = require('../routes/parkPlaceRouter')
const paymentProcessRouter = require('../routes/paymentProcessRouter')
const reservationRouter = require('../routes/reservationRouter')
const salesPoliciesRouter = require('../routes/salesPoliciesRouter')

router.use('/bonusesCosts', bonusesCostRouter)
router.use('/tariffPlans', tariffPlanRouter)
router.use('/users', userRouter)
router.use('/vehicles', vehicleRouter)
router.use('/subscriptions', subscriptionProcessRouter)
router.use('/payments', paymentProcessRouter)
router.use('/deposits', depositProcessRouter)
router.use('/cancellationPolicies', cancellationPoliciesRouter)
router.use('/favouriteParkings', favouriteParkingRouter)
router.use('/parkingActions', parkingActionRouter)
router.use('/parkings', parkingRouter)
router.use('/parkPlaces', parkPlaceRouter)
router.use('/reservations', reservationRouter)
router.use('/salesPolicies', salesPoliciesRouter)
router.use('/openAI', openAIRouter)


module.exports = router